# Generated by Django 2.2.6 on 2019-12-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_auto_20191202_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
